trigger:
- main

pool:
  name: 'windows'

lockBehavior: sequential

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: |
    echo "Running build..."
    dotnet build DemoApp.csproj > pipeline.log 2>&1
    echo Build exit code: %ERRORLEVEL%
    exit /b %ERRORLEVEL%
  displayName: 'Build .NET App - NuGet Restore Failure'

- script: |
    echo "===== PIPELINE LOGS ====="
    type pipeline.log
  displayName: 'Print Logs'
  condition: failed()

- script: |
    python --version
    pip install requests
  displayName: 'Install Python deps'
  condition: failed()

- script: |
    python analyze_logs.py
  displayName: 'Run AI Log Analysis (Ollama)'
  condition: failed()